### ISSUE TITLE
Celo plugin: no feedback on deployment, errors and success

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-plugins-directory#109]
Deploying doesn't show me any feedback on errors or success,
for example this happened to me and I found it in the console:

```
App.js:73 Error: insufficient funds for gas * price + value + gatewayFee
```
_All errors should be visible in the plugin UI and there should be information on what to do next to fix them._

_If it works there should be a message that the deployment was successful and what to do next._

**Comment by daoauth** [comment]
Yes, I'll add it.

**Comment by daoauth** [comment]
![Screen Shot 2020-11-04 at 12 10 49 PM](https://user-images.githubusercontent.com/57783762/98065062-12d86a80-1e97-11eb-82ff-cf586082ae16.png)
