### ISSUE TITLE
Celo plugin: using input fields when there is no input required from the user

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-plugins-directory#110]
Fields such as language, filename, account and the empty input next to the link button are input fields that don't accept inputs. This might be confusing. There are only real input fields in the contract and the 2 dropdowns.

**Comment by daoauth** [comment]
Yes, I'll fix it. But, account is required. Used when connecting with MetaMask.

**Comment by bunsenstraat** [comment]
But you can't actually type something in that field? it is automatically filled, so then why should it be an input field? Am I seeing this correctly?

**Comment by daoauth** [comment]
When a user first uses the plugin, pressing the Connect button will connect to the MetaMask and the account is automatically entered. And if you change the Account in MetaMask, it will also change. RemixIDE's DEPLOY & RUN TRANSACTIONS plugin's account field also changes according to MetaMask's account change. I used this as a reference. When the user first uses the plugin, I think there should be a button to connect with MetaMask explicitly.
