### ISSUE TITLE
Celo plugins: confusing use of buttons

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-plugins-directory#111]
There are two buttons next to each other, one for deploying and one 'link' button. One is a text button and one is an icon. 
Probably better to use a text for the link button clearly stating what it will do, for example, 'View on Etherscan'. 
Also, the link button remains inactive until the deploy button has been used. It might make more sense to have the deployment button first, which is used, and then display the result and the link button.

**Comment by daoauth** [comment]
Yes, I'll fix it.

**Comment by daoauth** [comment]
![Screen Shot 2020-11-04 at 12 18 03 PM](https://user-images.githubusercontent.com/57783762/98065361-d0635d80-1e97-11eb-8805-316dde45ff1b.png)

![Screen Shot 2020-11-04 at 12 15 57 PM](https://user-images.githubusercontent.com/57783762/98065302-add14480-1e97-11eb-8f9a-a65264129763.png)
