### ISSUE TITLE
Celo plugin: compile button?

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-plugins-directory#112]
Wouldn't it be easier to start compiling from the plugin?
https://github.com/ethereum/remix-plugin/blob/master/packages/api/doc/solidity.md
You can get the current file or read all the files using the filesystem
https://github.com/ethereum/remix-plugin/blob/master/packages/api/doc/file-system.md

When you compile you should display the compilation results.

**Comment by daoauth** [comment]
Yes, I'll add it.

**Comment by daoauth** [comment]
![Screen Shot 2020-11-04 at 12 10 49 PM](https://user-images.githubusercontent.com/57783762/98065062-12d86a80-1e97-11eb-82ff-cf586082ae16.png)
