### ISSUE TITLE
Celo plugin: clear navigation and steps

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-plugins-directory#114]
It might be better to really _guide the user_ in the UI, so that the user knows what to do and the information and inputs are gradually displayed as the user progresses. 

So for example, first you tell the user to load a sol file, when the file is loaded and selected then you display the compile button ( if possible ) and when the compilation is successful you can display the metamask button, chain selector and then the contract selector and so so on. You can do this with pages or collapsible divs, accordions or whatever makes it nice.

You should also have the ability to go back or start over again. 

If at all possible provide tooltips where you can and always show feedback from action.

**Comment by daoauth** [comment]
Yes, I'll add tooltips.

**Comment by daoauth** [comment]
![Screen Shot 2020-11-04 at 12 03 28 PM](https://user-images.githubusercontent.com/57783762/98065143-40251880-1e97-11eb-9fbe-9240e35ed641.png)
