### ISSUE TITLE
Celo plugin: dummy/demo data

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-plugins-directory#115]
It can be useful/fun/interesting for your user to be able to load a demo contract that demonstrates the use of the plugin. You could use the filesystem of Remix, https://github.com/ethereum/remix-plugin/blob/master/packages/api/doc/file-system.md, to load a file if the user wants to or load it by default. Don't know if it makes sense in this usecase?

**Comment by daoauth** [comment]
Since the solidity code is the same as ethereum, I don't think we need a dedicated example.

**Comment by bunsenstraat** [comment]
Ok! If you say so.
