### ISSUE TITLE
Plugin Zokrates: download buttons do nothing

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-plugins-directory#172]
The various download buttons in the plugin don't do anything.

**Comment by dark64** [comment]
This seems like an issue with remix not allowing downloads in the iframe. I guess, this restriction could be lifted by adding `allow-downloads` keyword to the iframe sandbox attribute list. I'm not sure about security though, maybe allow only for some plugins?

**Comment by bunsenstraat** [comment]
@yann300 let's find an answer to this issue, see if we can implement the allow downloads for some plugins.

**Comment by bunsenstraat** [comment]
@dark64 is there an update for this?

**Comment by dark64** [comment]
Unfortunately no, this should be discussed within the Remix team as Google Chrome release 83 and above started disallowing iframes from downloading unless the `allow-downloads` key is added to an iframe’s sandbox attributes ([see here](https://www.chromestatus.com/feature/5706745674465280)). I'm not sure if this should be a default for all plugins, but there should be a way for plugins to request this permission, maybe by adding needed sandbox attributes to plugin's `profile.json`?

**Comment by dark64** [comment]
Just a quick update on this, we decided to remove all download buttons and structure the plugin in a way that artifacts can be opened in the remix editor directly. I guess this issue is no longer relevant and can be closed.
