### ISSUE TITLE
Plugin Walletconnect:  Not activating

### ISSUE THREAD

**Issue by lukemorales1** [ethereum/remix-plugins-directory#289]
Hey team,

I am trying to activate the walletconnect plugin since yesterday and it seems like the button is not responding. I tried accessing the IPFS URL of the walletconnect from the plugins folder here as well but it doesn't seem to load up. Can someone please help me with it?

FYI,
I am currently using MacOS 11.3 on a Macbook Pro i5
I have tried using remix within a browser and also by downloading the dmg file.

**Comment by yann300** [comment]
we had some issues with the ipfs node, this should be ok now, can you try it again?
